# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Unicode-DFS-2016",
]

[bans]
multiple-versions = "deny"
skip = [
     { name = "bitflags", version = "1.3.2" },
     { name = "rsa", version = "0.9.4" },
]

[advisories]
# See https://github.com/RustCrypto/RSA/issues/19#issuecomment-1822995643.
# There is no workaround available yet.
ignore = ["RUSTSEC-2023-0071"]
